# Configurações de acesso ao banco
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/apicdc?createDatabaseIfNotExist=true"
    username: "user_app"
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
    database-platform: org.hibernate.dialect.MySQL57Dialect

#custumer configurations
br:
  com:
    vfs:
      api:
        casadocodigo:
          bean-validation:
            unique-value: this a unique value field and that value exist in our database